function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 26-May-2016 11:08:55

% Create figure
figure1 = figure('name','CDF UEs Throughput [bps/Hz]');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.067238912732475 0.122522522522523 0.875536480686695 0.747747747747748]);
hold(axes1,'on');

% Create plot
plot(X1, Y1,'DisplayName','NS3 Case1 3D (Full Buffer)','Color', 'green');

% Create xlabel
xlabel('Normalized User Throughput [bps/Hz]');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 0.5]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on','YMinorTick','on','YTick',...
    [0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],'YTickLabel',...
    {'0','10','20','30','40','50','60','70','80','90','100'},...
    'XTick', [0 0.1 0.2 0.3 0.4 0.5]);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.62899380429165 0.197597598403066 0.263233184174918 0.0342342334287661]);

