function ns3

%Killing any session created with previous parpool
delete(gcp('nocreate'));

%creating cluster of numThreads workers for parfor (#numThreads threads)
numThreads = 5;
sampleSize = 30; %prefferably multiple of 5 to optimally use the max threads allowed
parpool(numThreads, 'IdleTimeout', Inf);

%configuring each thread with the 3GPP requirements
    parfor i=1:sampleSize

        dlrlcFile = ['run_' num2str(i) '_DlRlcStats.txt'];
        sinrFile = ['run_' num2str(i) '_DlRsrpSinrStats.txt'];
        %rsrqFile = ['run_' i '_rsrq_log.txt'];
        disp(['Run ' num2str(i)])
        wafString = ['./waf --run "lena-dual-stripe' ...
          ' --simTime=5.4 --nMacroEnbSites=19 --nMacroEnbSitesX=4' ...
          ' --epc=1 --epcDl=1 --epcUl=0 --outdoorUeMinSpeed=0.833 --outdoorUeMaxSpeed=0.833' ...
          ' --macroUeDensity=0.00001' ...
          ' --macroEnbBandwidth=100' ...
          ' --ns3::LteEnbNetDevice::DlBandwidth=50' ...
          ' --ns3::LteEnbNetDevice::UlBandwidth=50' ...
          ' --ns3::LteSpectrumPhy::CtrlErrorModelEnabled=true' ...
          ' --ns3::LteSpectrumPhy::DataErrorModelEnabled=true' ...
          ' --ns3::LteAmc::Ber=0.00005' ...
          ' --ns3::LteEnbRrc::DefaultTransmissionMode=1' ...
          ' --macroEnbTxPowerDbm=46' ...
          ' --ns3::LteHelper::Scheduler=ns3::RrFfMacScheduler' ...
          ' --ns3::LteHelper::HandoverAlgorithm=ns3::A2A4RsrqHandoverAlgorithm' ...
          ' --ns3::RadioBearerStatsCalculator::EpochDuration=5.0' ...
          ' --ns3::RadioBearerStatsCalculator::StartTime=0.4' ...
          ' --ns3::RadioBearerStatsCalculator::DlRlcOutputFilename=' dlrlcFile ...
          ' --ns3::PhyStatsCalculator::DlRsrpSinrFilename=' sinrFile ...
          ' --RngRun=' num2str(i) ...
          ' --generateRem=false --remRbId=-1 --useUdp=false"'];
          system(wafString);
        %compute_script(dlrlcFile,sinrFile,rsrqFile);
    end

end